rules:
# Benefit Wallet
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Benefit Wallet
          case_sensitive: true
    actions:
      - move: ~/Documents/Receipts/Medical/Benefit_Wallet/
# Target Card
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Target Card
          case_sensitive: true
    actions:
      - move: /home/wadeallen/Documents/Statements/Target/
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Housing Receipt
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Receipts/Housing/Misc Housing/"
# Wedding Covid Releases
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Wedding_Covid_Release
          case_sensitive: true
    actions:
      - move: /home/wadeallen/Documents/Wedding_Releases/
# Vectren
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Vectren Bill
          case_sensitive: true
    actions:
      - move: /home/wadeallen/Documents/Receipts/Housing/Utilities/Gas/
# Three Rivers
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Three Rivers Credit Union
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Statements/Three Rivers Credit Union/"
# Thrivent Rivers
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Thrivent Credit Union
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Statements/Thrivent Credit Union/"
# Yorktown Municipal Utilities
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Yorktown Municipal Utilities
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Receipts/Housing/Utilities/Water/"
# Indiana Michigan Power 
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - I&MBill_
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Receipts/Housing/Utilities/Electric/"
# Maurices
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Maurices Statement
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Statements/Maurices/"
# Teachers Credit Union
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - Teachers Credit Union
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Statements/Teachers Credit Union/"
# Evansville Teachers Credit Union
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - Evansville Teachers Credit Union
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Statements/Evansville Teachers Credit Union/"
# Budget Reports 
  - folders: ~/Desktop
    subfolders: false
    filters:
      - extension: pdf
      - regex: '\d\d\d\d-\d\d_Balance_Sheet'
    actions:
      - move: "/home/wadeallen/Documents/Administration/Budget_Reports/"
# Budget Reports 
  - folders: ~/Desktop
    subfolders: false
    filters:
      - extension: pdf
      - regex: '\d\d\d\d-\d\d_Profit_Loss'
    actions:
      - move: "/home/wadeallen/Documents/Administration/Budget_Reports/"
# Caresource
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - CareSource Health Insurance
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Receipts/Insurance/CareSource/"
# Anna Vanderbilt Insurance
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - Anna Vanderbilt Health Insurance
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Anna/Anna_Vanderbilt/"
# Kohls
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - Kohls Statement
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Statements/Kohls/"
# TJ Maxx
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - TJ Maxx Statement
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Receipts/TJ Maxx/"
# Ball State Credit Union
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - Ball State Credit Union
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Receipts/Ball_State_Credit_Union/"
# Verizon Wireless
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - Verizon
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Receipts/Wireless_Phone/Verizon/"
# United Church Receipts
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - United Church Receipt
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Receipts/United Church Receipts/"
# RG&E Statements
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - RGEBill
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Receipts/Housing/Utilities/Electric/"
# Offering Count
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Offering_Count
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Offering_Count/"
# ISOE Grant
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Paycheck Stub ISOE Grant
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/ISOE/"
# MVP Explanation of Benefits
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - _mvp_eob
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Receipts/Insurance/MVP/EOB Statements/"
# City Mini Storage Receipts
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - _City_Mini_Storage
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Housing/City_Storage/"
# U of R Medicine
  - folders: ~/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - _UofR_Medicine
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Documents/Medical/UofR_Medicine/"
