rules:
# Benefit Wallet
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Benefit Wallet
          case_sensitive: true
    actions:
      - move: ~/Dropbox/Receipts/Medical/Benefit_Wallet/
# Target Card
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Target Card
          case_sensitive: true
    actions:
      - move: /home/wadeallen/Dropbox/Statements/Target/
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Housing Receipt
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Receipts/Housing/Misc Housing/"
# Wedding Covid Releases
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Wedding_Covid_Release
          case_sensitive: true
    actions:
      - move: /home/wadeallen/Dropbox/Wedding_Releases/
# Vectren
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Vectren Bill
          case_sensitive: true
    actions:
      - move: /home/wadeallen/Dropbox/Receipts/Housing/Utilities/Gas/
# Three Rivers
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Three Rivers Credit Union
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Statements/Three Rivers Credit Union/"
# Thrivent Rivers
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Thrivent Credit Union
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Statements/Thrivent Credit Union/"
# Church Receipts 
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Church Receipt
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Receipts/Church/Current/"
# Yorktown Municipal Utilities
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Yorktown Municipal Utilities
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Receipts/Housing/Utilities/Water/"
# Indiana Michigan Power 
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - I&MBill_
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Receipts/Housing/Utilities/Electric/"
# Maurices
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          contains:
            - Maurices Statement
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Statements/Maurices/"
# Teachers Credit Union
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - Teachers Credit Union
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Statements/Teachers Credit Union/"
# Evansville Teachers Credit Union
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - Evansville Teachers Credit Union
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Statements/Evansville Teachers Credit Union/"
# Budget Reports 
  - folders: ~/Desktop
    subfolders: false
    filters:
      - extension: pdf
      - regex: '\d\d\d\d-\d\d_Balance_Sheet'
    actions:
      - move: "/home/wadeallen/Dropbox/Administration/Budget_Reports/"
# Budget Reports 
  - folders: ~/Desktop
    subfolders: false
    filters:
      - extension: pdf
      - regex: '\d\d\d\d-\d\d_Profit_Loss'
    actions:
      - move: "/home/wadeallen/Dropbox/Administration/Budget_Reports/"
# Caresource
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - CareSource Health Insurance
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Receipts/Insurance/CareSource/"
# Anna Vanderbilt Insurance
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - Anna Vanderbilt Health Insurance
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Anna/Anna_Vanderbilt/"
# Kohls
  - folders: ~/Dropbox/Scans
    subfolders: false
    filters:
      - extension: pdf
      - filename:
          startswith:
            - Kohls Statement
          case_sensitive: true
    actions:
      - move: "/home/wadeallen/Dropbox/Statements/Kohls"
