#! /bin/bash

sunday=$(date -d"Sunday +1 week" +%Y-%m-%d)
subjectday=$(date -d"$sunday" "+%B %d")

source ~/bin/read_yaml
create_variables ~/Dropbox/Administration/Markdown_Files/Sermon_Work/${sunday}*.md








