#! /bin/bash

day=$1

if  [ -z "$day" ]; then
  sunday=`date -d"Sunday" +%Y-%m-%d`
else
  sunday=`date -d"$day" +%Y-%m-%d`
fi

dayName=`date -d"$sunday" +%a | tr '[:lower:]' '[:upper:]'`
if [ $dayName = "SUN" ] ; then
  sunday_date=$sunday
  source ~/bin/read_yaml
  create_variables ~/Dropbox/Administration/Markdown_Files/Sermon_Work/${sunday_date}*.md
  echo $title
  echo $scripture
else
  echo Please enter a Sunday
fi








